Algoritmo "Questão03"
// Disciplina   : LÓGICA DE PROGRAMAÇÃO
// Professor   : FABRÍCIO CURVELLO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/05/2024
Var
// Seção de Declarações das variáveis 
   dolar:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Quantos dólare devo converter? ")
   leia(dolar)
   escreva("Você tem ",dolar*1.72," reais")

Fimalgoritmo