Algoritmo "Questão04"
// Disciplina   : LÓGICA DE PROGRAMAÇÃO
// Professor   : FABRÍCIO CURVELLO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/05/2024
Var
// Seção de Declarações das variáveis 
   num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Escreva um número inteiro: ")
   leia(num)
   escreva("Seu antecessor é ", num-1," e seu sucessor é ",num+1)

Fimalgoritmo